# Generated by Django 3.1.2 on 2020-10-31 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Chapter', models.CharField(max_length=100)),
                ('Obtainable', models.BooleanField(default=True)),
                ('Cost', models.IntegerField()),
                ('On_Play_Effect', models.TextField()),
                ('Dice_Number', models.IntegerField()),
                ('ImgPath', models.CharField(max_length=300)),
                ('Roll1', models.CharField(blank=True, max_length=10, null=True)),
                ('Eff1', models.CharField(blank=True, max_length=200, null=True)),
                ('Roll2', models.CharField(blank=True, max_length=10, null=True)),
                ('Eff2', models.CharField(blank=True, max_length=200, null=True)),
                ('Roll3', models.CharField(blank=True, max_length=10, null=True)),
                ('Eff3', models.CharField(blank=True, max_length=200, null=True)),
                ('Roll4', models.CharField(blank=True, max_length=10, null=True)),
                ('Eff4', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Creator', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Effects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Story', models.TextField()),
                ('ImgPath', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Description', models.TextField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RelDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.card')),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.deck')),
            ],
        ),
        migrations.CreateModel(
            name='Rel_Page_Eff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Effects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.effects')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.page')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Info', models.TextField()),
                ('ImgPath', models.CharField(max_length=300)),
                ('Rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.rank')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Story', models.TextField()),
                ('ImgPath', models.CharField(max_length=300)),
                ('Office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.office')),
                ('Page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.page')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='Office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.office'),
        ),
    ]
