# Generated by Django 3.1.2 on 2020-10-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='Slogan',
            field=models.CharField(default='I go out to the street, my hands in my pockets.', max_length=100),
            preserve_default=False,
        ),
    ]
