# Generated by Django 3.1.2 on 2020-10-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0002_rank_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='Slogan',
            field=models.CharField(max_length=200),
        ),
    ]
