# Generated by Django 3.1.2 on 2020-10-31 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0003_auto_20201031_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='ImgPath',
            field=models.CharField(default='Lor_Data/Canard.png', max_length=300),
            preserve_default=False,
        ),
    ]
