# Generated by Django 3.1.2 on 2020-11-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0004_rank_imgpath'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='deck',
            name='Slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='effects',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='rel_page_eff',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='reldeck',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
