# Generated by Django 3.1.2 on 2020-11-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0005_auto_20201031_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='Rarity',
            field=models.CharField(choices=[('P', 'Paperback'), ('L', 'Limited'), ('H', 'Hardcover'), ('O', "Objet d'art"), ('E', 'EGO')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='card',
            name='Type1',
            field=models.CharField(choices=[('BL', 'Blunt'), ('PI', 'Pierce'), ('SL', 'Slash'), ('EV', 'Evade'), ('BO', 'Block')], default='BL', max_length=2),
        ),
        migrations.AddField(
            model_name='card',
            name='Type2',
            field=models.CharField(choices=[('BL', 'Blunt'), ('PI', 'Pierce'), ('SL', 'Slash'), ('EV', 'Evade'), ('BO', 'Block')], default='BL', max_length=2),
        ),
        migrations.AddField(
            model_name='card',
            name='Type3',
            field=models.CharField(choices=[('BL', 'Blunt'), ('PI', 'Pierce'), ('SL', 'Slash'), ('EV', 'Evade'), ('BO', 'Block')], default='BL', max_length=2),
        ),
        migrations.AddField(
            model_name='card',
            name='Type4',
            field=models.CharField(choices=[('BL', 'Blunt'), ('PI', 'Pierce'), ('SL', 'Slash'), ('EV', 'Evade'), ('BO', 'Block')], default='BL', max_length=2),
        ),
    ]
