# Generated by Django 3.1.2 on 2020-11-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0006_auto_20201101_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='Chapter',
        ),
    ]
