# Generated by Django 3.1.2 on 2020-11-02 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0007_remove_card_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Dice_Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='ImgPath',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='On_Play_Effect',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Rarity',
            field=models.CharField(choices=[('P', 'Paperback'), ('L', 'Limited'), ('H', 'Hardcover'), ('O', "Objet d'art"), ('E', 'EGO')], default='P', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Type1',
            field=models.CharField(blank=True, choices=[('BL', 'Blunt'), ('PI', 'Pierce'), ('SL', 'Slash'), ('EV', 'Evade'), ('BO', 'Block')], default='BL', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Type2',
            field=models.CharField(blank=True, choices=[('BL', 'Blunt'), ('PI', 'Pierce'), ('SL', 'Slash'), ('EV', 'Evade'), ('BO', 'Block')], default='BL', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Type3',
            field=models.CharField(blank=True, choices=[('BL', 'Blunt'), ('PI', 'Pierce'), ('SL', 'Slash'), ('EV', 'Evade'), ('BO', 'Block')], default='BL', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='Type4',
            field=models.CharField(blank=True, choices=[('BL', 'Blunt'), ('PI', 'Pierce'), ('SL', 'Slash'), ('EV', 'Evade'), ('BO', 'Block')], default='BL', max_length=2, null=True),
        ),
    ]
