# Generated by Django 3.1.2 on 2020-11-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0008_auto_20201101_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='Slug',
        ),
        migrations.RemoveField(
            model_name='effects',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='rel_page_eff',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='reldeck',
            name='slug',
        ),
    ]
