# Generated by Django 3.1.2 on 2020-11-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0009_auto_20201102_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='deck',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='Name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
