# Generated by Django 3.1.2 on 2020-11-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0011_auto_20201102_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='ImgPath',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
