# Generated by Django 3.1.2 on 2020-11-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0012_auto_20201103_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='ImgPath',
        ),
        migrations.AddField(
            model_name='page',
            name='Rarity',
            field=models.CharField(choices=[('P', 'Paperback'), ('L', 'Limited'), ('H', 'Hardcover'), ('O', "Objet d'art"), ('E', 'EGO')], default='P', max_length=1, null=True),
        ),
    ]
