# Generated by Django 3.1.2 on 2020-11-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0013_auto_20201103_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='effects',
            name='InGameId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
