# Generated by Django 3.1.2 on 2020-11-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0014_effects_ingameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='effects',
            name='InGameId',
            field=models.IntegerField(unique=True),
        ),
    ]
