# Generated by Django 3.1.2 on 2020-11-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0015_auto_20201106_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='InGameId',
            field=models.IntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
