# Generated by Django 3.1.2 on 2020-11-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0016_page_ingameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='Story',
            field=models.TextField(null=True),
        ),
    ]
