# Generated by Django 3.1.2 on 2020-11-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0017_auto_20201106_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ImgPath',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
