# Generated by Django 3.1.2 on 2020-11-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0018_auto_20201106_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='On_Play_Effect',
            field=models.TextField(blank=True, null=True),
        ),
    ]
