# Generated by Django 3.1.2 on 2020-11-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0021_card_cardtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Rarity',
            field=models.CharField(choices=[('P', 'Paperback'), ('H', 'Hardcover'), ('L', 'Limited'), ('O', "Objet d'art"), ('E', 'EGO')], default='P', max_length=1, null=True),
        ),
    ]
