# Generated by Django 3.1.2 on 2020-11-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0022_auto_20201107_0159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='Creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='deck',
            old_name='Name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(to='LoR.Card'),
        ),
        migrations.AddField(
            model_name='page',
            name='InitialEffects',
            field=models.ManyToManyField(to='LoR.Effects'),
        ),
    ]
