# Generated by Django 3.1.2 on 2020-11-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0023_auto_20201108_1817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelDeck',
        ),
    ]
