# Generated by Django 3.1.2 on 2020-11-09 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0024_delete_reldeck'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.card')),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.deck')),
            ],
        ),
        migrations.RemoveField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='LoR.RelDeck', to='LoR.Card'),
        ),
    ]
