# Generated by Django 3.1.2 on 2020-11-09 05:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0025_auto_20201108_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='cards',
            field=models.ManyToManyField(through='LoR.RelDeck', to='LoR.Card'),
        ),
        migrations.AddField(
            model_name='reldeck',
            name='card_count',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
