# Generated by Django 3.1.2 on 2020-11-09 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0026_auto_20201108_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reldeck',
            name='card_count',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(0)]),
        ),
    ]
