# Generated by Django 3.1.2 on 2020-11-10 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0027_auto_20201108_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='Office',
        ),
        migrations.DeleteModel(
            name='Rel_Page_Eff',
        ),
    ]
