# Generated by Django 3.1.2 on 2020-11-10 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0028_auto_20201109_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LoR.office'),
        ),
    ]
