# Generated by Django 3.1.2 on 2020-11-10 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0030_auto_20201110_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='office',
            new_name='Office',
        ),
    ]
