# Generated by Django 3.1.2 on 2020-11-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0031_auto_20201110_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='InitialEffects',
            field=models.ManyToManyField(blank=True, to='LoR.Effects'),
        ),
    ]
