# Generated by Django 3.1.2 on 2020-11-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0034_auto_20201113_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
