# Generated by Django 3.1.2 on 2020-11-17 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0036_auto_20201115_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='Recc_Floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LoR.office'),
        ),
        migrations.AddField(
            model_name='deck',
            name='Recc_Page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LoR.page'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='description',
            field=models.TextField(),
        ),
    ]
