# Generated by Django 3.1.2 on 2020-11-17 06:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LoR', '0037_auto_20201116_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('Recc_Floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LoR.office')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RelGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_count', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)])),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.deck')),
                ('guide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LoR.guide')),
            ],
        ),
        migrations.AddField(
            model_name='guide',
            name='required_decks',
            field=models.ManyToManyField(through='LoR.RelGuide', to='LoR.Deck'),
        ),
    ]
