# Generated by Django 3.1.2 on 2020-12-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0042_auto_20201129_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='office',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='rank',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
