# Generated by Django 3.1.2 on 2020-12-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LoR", "0044_auto_20201221_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="Recc_Rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="LoR.rank",
            ),
        ),
    ]
