# Generated by Django 3.1.2 on 2020-12-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0045_deck_recc_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
