# Generated by Django 3.1.2 on 2020-12-30 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0046_deck_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbnoCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('effects', models.TextField()),
                ('description', models.TextField()),
                ('ImgPath', models.CharField(blank=True, max_length=200)),
                ('Office', models.ForeignKey(limit_choices_to={'Rank': 7}, on_delete=django.db.models.deletion.CASCADE, to='LoR.office')),
            ],
        ),
    ]
