# Generated by Django 3.1.2 on 2020-12-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0047_abnocards'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnocards',
            name='emotion_type',
            field=models.CharField(blank=True, choices=[('BD', 'Breakdown page'), ('AW', 'Awakening page')], default='AW', max_length=2),
        ),
    ]
