# Generated by Django 3.1.2 on 2020-12-30 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoR', '0048_abnocards_emotion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='abnocards',
            name='emotion_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
    ]
